const sampleProject = {
    id: '1',
    name: 'E-Commerce Platform',
    description: 'A modern e-commerce platform built with Next.js and Tailwind CSS',
    mainImage: '/bpayHero.png',
    screenshots: [
        '/TABHero.png',
        '/bpayHero.png',
        '/bpayHero.png',
    ],
    videos: [
        '/bpayHero.png',
        '/bpayHero.png',
    ],
    about: 'This project is a full-stack e-commerce solution featuring user authentication, product management, shopping cart functionality, and payment integration. Built with modern web technologies and best practices.',
    links: {
        live: 'https://example.com',
        github: 'https://github.com/akorede12/project',
        demo: 'https://youtube.com/demo-video',
    },
    technologies: [
        'Next.js',
        'TypeScript',
        'Tailwind CSS',
        'Node.js',
        'MongoDB',
        'Stripe',
        'NextAuth',
    ],
    contributions: [
        'Implemented user authentication system',
        'Developed product catalog and search functionality',
        'Integrated payment processing with Stripe',
        'Optimized performance and SEO',
        'Built responsive UI components',
    ],
    contributors: [
        {
            name: 'Akorede',
            role: 'Full Stack Developer',
            avatar: '/Me2.jpg',
        },
        {
            name: 'Akorede',
            role: 'UI/UX Designer',
            avatar: '/Me2.jpg',
        },
    ],
};

const ProjectData = [
    {
        id: '1',
        name: 'The Open Protocol',
        description: 'hybrid trading infrastructure',
        mainImage: '/topx.png',
        screenshots: [
            '/topx.png',
            '/topx2.png',
            '/topx3.png',
            '/topx4.png',
            '/topx5.png',
        ],
        videos: [
            '/topx.png',
        ],
        about: "TOP (The Open Protocol) is more than just another token — it's a revolutionary hybrid trading infrastructure designed to merge the best of both worlds: the speed and liquidity of centralized exchanges(CEXs) with the security and transparency of decentralized protocols(DEXs).The TOP Airdrop rewards early supporters and welcomes a global community built on trust, innovation, and transparency.",
        links: {
            live: 'https://www.theopenprotocol.com/',
            github: 'https://github.com/topxairdrop/smartContracts',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'solana-web3js',
            'anchor',
            'Solana',
        ],
        contributions: [
            'Built, tested, and deployed TOPx Solana Smart Contract',
            'Developed and Deployed TOPx Tokens on Solana',
            'Integrated advanced user, user tasks and user token tracking features to smart contract',
            'Optimized Topx airdrop and gamified features',
            'Created advanced task creation and tracking features for TOPx airdrop',
            'Created integration script for frontend Nextjs Dapp'
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Blockchain Developer(Solana)',
                avatar: '/Me2.jpg',
            },
            {
                name: 'Devlight/ delightmayy',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '23',
        name: 'A Token Presale Waitlist',
        description: 'A waitlist page for a Token presale',
        mainImage: '/waitlist1.png',
        screenshots: [
            '/waitlist1.png',
            '/waitlist2.png',
            '/waitlist3.png',
            '/waitlist4.png',
            '/waitlist5.png',
        ],
        videos: [
            'waitlist1.png',
        ],
        about: "A modern, responsive waitlist management platform built with Next.js, TypeScript, and Tailwind CSS for the Salamanda digital asset ecosystem. Features: User - Facing Features Elegant Waitlist Form - Beautiful, responsive signup form with interactive elements Multiple Interest Options - Users can select from various asset types(Real Estate, Music, Agriculture, etc.) Engagement Types - Options for asset digitization, learning, and early access opportunities Mobile - First Design - Fully responsive across all device sizes Modern UI / UX - Clean design with smooth animations and intuitive interactions Admin Features. Dashboard Overview - Comprehensive view of all waitlist registrations Advanced Filtering - Filter by engagement type(Digitizing, Learning, Early Access) Real - time Statistics - Visual metrics and counts for quick insights Demo Data Ready - Built -in sample data for testing and demonstration Responsive Admin Interface - Manage registrations from any device Tech Stack Framework: Next.js 14 with App Router Language: TypeScript Styling: Tailwind CSS Icons: Custom SVG icons Fonts: Atyp Display & Manrope State Management: React Hooks(useState useEffect) ",
        links: {
            live: '',
            github: 'https://github.com/akorede1/presale-waitlist',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
        ],
        contributions: [
            'Developed dynamic buttons for waitlist form',
            'Developed dynamic waitlist form',
            'Developed project timeline section',
            'Developed admin dashboard to monitor waitlist registrations',
            'Built responsive UI components',
            'Implemented user authentication system',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '2',
        name: 'SmartInvest',
        description: 'Cross-chain Crypto Currency hedging platform',
        mainImage: '/SmartInvestHero.png',
        screenshots: [
            '/SmartInvestHero.png',
        ],
        videos: [
            '/SmartInvestHero.png',
        ],
        about: 'Smart Invest is a decentralized finance (DEFI) application designed to protect users BTC (and other Crypto currency) holdings from market downturns through automated cross-chain hedging. it enables users to deposit Bitcoin( or wrapped Bitcoin WBTC) on Base or Solana chain, automatically converts BTC to USDC on Base during the periods of high volatility or in a market downturn. Cross- chain communication is facilitated by chainlink CCIP, allowing seamless message and token flow between Base(EVM) and Solana(SVM).',
        links: {
            live: '',
            github: 'https://github.com/akorede12/SmartInvest/',
            demo: '',
        },
        technologies: [
            'Solidity',
            'Rust',
            'Chainlink',
            'Node.js',
        ],
        contributions: [
            'Built solidity and rust smart contracts',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Founder, Blockchain Developer(Solana)',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '3',
        name: 'Appware',
        description: 'Social Application Platform',
        mainImage: '/AppwareHero.png',
        screenshots: [
            '/AppwareHero.png',
        ],
        videos: [
            '/AppwareHero.png',
        ],
        about: 'Appware is a social application platform that allows users to create and manage their own social applications. It provides a user-friendly interface for app developers and users to easily interact with each other, and includes features such as Developer messaging commenting on app updates, and social media integration.',
        links: {
            live: 'https://appware-app.vercel.app/',
            github: 'https://github.com/Appware-app/Appware-Frontend-V1',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
        ],
        contributions: [
            'Team Lead',
            'Contributed to the development of the frontend',
            'Built responsive UI components',
            'Optimized performance and SEO',
            'Coordinated with backend developers to ensure smooth integration',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Frontend Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'mrted: Demenenge Thaddeaus Iorbee',
                role: 'Fullstack Developer',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '4',
        name: 'Shoppleverse: E-Commerce Platform',
        description: 'A modern web3 e-commerce platform',
        mainImage: '/shopple1.png',
        screenshots: [
            '/shopple1.png',
            '/shopple2.png',
            '/shopple3.png',
            '/shopple4.png',
            '/shopple5.png',
        ],
        videos: [
            '/shopple1.png',
        ],
        about: 'Shoppleverse is a modern web3 e-commerce platform that allows users to buy and sell products on the blockchain. It provides a user-friendly interface for buying and selling products, and includes features such as user authentication, product management, shopping cart functionality, and BNBpayment integration.',
        links: {
            live: 'https://shoppleverse-alt.vercel.app',
            github: 'https://github.com/ShoppleVerse/shoppleverse-alt',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'Ethers',
            'hardhat',
        ],
        contributions: [
            'Implemented onchain user login and authentication system',
            'Implemented onchain payment receipt functionality',
            'Integrated payment processing with BNB token',
            'Built, tested, deployed and integrated e-commerce smart contracts',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'Ridalord',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
            {
                name: 'ashrafolarinoye Ashraf',
                role: 'Backend Developer',
                avatar: '/user.png',
            },
            {
                name: 'preciousnwaoha Precious Nwaoha',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
            {
                name: 'oluwatobi2001',
                role: 'Developer',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '5',
        name: 'Boundless Pay',
        description: 'Cross-chain DEFI platform: Staking Bridging and Token Purchase',
        mainImage: '/bpayHero.png',
        screenshots: [
            '/bpay1.png',
            '/bpay2.png',
            '/bpay3.png',
            '/bpay4.png',
            '/bpay5.png',
        ],
        videos: [
            '/bpayHero.png',
        ],
        about: 'Boundless Pay is a cross-chain web3 DEFI platform that allows users buy bpay tokens, stake tokens to earn rewards, and bridge tokens between blockchains.',
        links: {
            live: 'https://www.bpaystaking.com/',
            github: 'https://github.com/akorede12/project',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'Ethers',
            'hardhat',
            'RainbowKit Wallet',
        ],
        contributions: [
            'Created and deployed BoundlesPay Token on Base ',
            'Created and deployed BoundlesPay Staking Contract on Base',
            'Created and deployed BoundlesPay Bridge Contract on Base',
            'Created and deployed BoundlesPay Bridge Contract on BNB smart chain',
            'Created offchain relayer to handle token bridging',
            'Smart contract integration to Boundless Pay platform',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'uche7 Nnajiofor Uchenna',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
            {
                name: 'and more',
                role: 'Developer',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '19',
        name: 'Presale Token Sale Modal',
        description: 'Presale token sale modal built with Next.js, wagmi, ethers and Tailwind CSS',
        mainImage: '/salemodal.png',
        screenshots: [
            '/salemodal1.png',
            '/salemodal2.png',
            '/salemodal3.png',
            '/salemodal4.png',
            '/salemodal5.png',
            '/salemodal6.png',
            '/salemodal7.png',
        ],
        videos: [
            '/salemodal.png',
        ],
        about: "SaleModal is a comprehensive React TypeScript component that provides a multi-step modal interface for purchasing tokens during a cryptocurrency presale event. The component handles the complete user journey from token selection to purchase confirmation, integrating with blockchain smart contracts and multiple wallet providers.\n\nKey Features\n\n🚀 Multi - Step Purchase Flow\nBuy Page: Token amount selection with real - time conversion calculations   \nTerms of Service: Legal agreement with interactive checkbox\nWallet Connection: Support for multiple cryptocurrency wallets\nConfirmation: Purchase success with transaction details\n💳 Payment Options\nCryptocurrency Payments: ETH and USDC support\nReal - time Conversion: Live price feeds from CoinGecko API\nSmart Contract Integration: Direct interaction with presale contracts\nMulti - phase Pricing: Dynamic pricing based on current presale phase\n🔗 Wallet Integration\nMulti - wallet Support: MetaMask, Trust Wallet, Phantom, WalletConnect\nConnection Management: Robust error handling and user feedback\nBalance Tracking: Real - time token balance updates\n🛡️ Security & Compliance\nTerms Agreement: Legal compliance with interactive consent\nTransaction Validation: Pre - transaction simulation\nError Handling: Comprehensive error messaging and user feedback",
        links: {
            live: '',
            github: 'https://github.com/akorede12/token-sale-modal',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'ethers',
            'wagmi',
            'CoinGecko API',
        ],
        contributions: [
            'Implemented user wallet connection',
            'Implemented presale token sale modal',
            'Created receipt page',
            'Built responsive UI components',
            'Implemented Mobile-optimized interface',
            'Implemented Smooth scrolling and transitions',
            'Implemented Interactive notifications system',
            'Implemented Multi - wallet Support: MetaMask, Trust Wallet, Phantom, WalletConnect',
            'Implemented Connection Management: Robust error handling and user feedback',
            'Implemented Balance Tracking: Real - time token balance updates',
            'Implemented CoinGecko API for usdc / eth price for token price conversion',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '20',
        name: 'Tokenizer Blog',
        description: 'A blog built with Next.js and Tailwind CSS',
        mainImage: '/blog1.png',
        screenshots: [
            '/blog1.png',
            '/blog2.png',
            '/blog3.png',
            '/blog4.png',
            '/blog5.png',
            '/blog6.png',
            '/blog7.png',
        ],
        videos: [
            '/blog1.png',
        ],
        about: "The Tokenizer Blog Platform is a modern, feature-rich content management system built with Next.js, designed to showcase the company's innovations in asset tokenization and blockchain technology.This platform serves as the central hub for sharing insights, announcements, and educational content about tokenizing assets.",
        links: {
            live: '',
            github: 'https://github.com/akorede12/Blog',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
        ],
        contributions: [
            'Implemented Content Flexibility: Supports both structured content and raw Markdown/HTML',
            'Implemented Responsive Design: Optimized for desktop, tablet, and mobile devices',
            'ImplementedPerformance: Efficient loading states and error handling',
            'Implemented Accessibility: Proper semantic HTML and keyboard navigation',
            'Implemented SEO-Friendly: Meta tags and structured content for search engines',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '21',
        name: 'Content Management System',
        description: 'Content Management System built with Next.js and Tailwind CSS',
        mainImage: '/cms1.png',
        screenshots: [
            '/cms1.png',
            '/cms2.png',
            '/cms3.png',
            '/cms4.png',
            '/cms5.png',
        ],
        videos: [
            '/cms1.png',
        ],
        about: 'The CMS Dashboard is a comprehensive content management system built with Nextjs and TypeScript, designed for creating, editing, and managing blog posts with a rich markdown editor interface.',
        links: {
            live: '',
            github: 'https://github.com/akorede12/cms',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'NextAuth',
            'Axios',
            'Lucide React',
            'Remarkable',
        ],
        contributions: [
            'Create, edit, and delete blog posts',
            'Implemented user authentication system',
            'Implemented RemarkableEditor with toolbar for easy formatting',
            'Implemented Real-time markdown preview',
            'Implemented Support for images, quotes, code blocks, and links',
            'Implemented Keyboard shortcuts and text insertion helpers',
            'Implemented SEO optimization fields (meta title, description, keywords)',
            'Implemented Loading states and error handling',
            'Implemented Confirmation dialogs for destructive actions',
            'Implemented Toggle publish status (draft/published)',
            'Implemented Feature post highlighting',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '22',
        name: 'Presale Token Dashboard',
        description: 'A comprehensive cryptocurrency presale management platform built with Next.js, featuring separate user and admin dashboards for managing token sales across multiple phases.',
        mainImage: '/dash1.png',
        screenshots: [
            '/dash1.png',
            '/dash2.png',
            '/dash3.png',
            '/dash4.png',
            '/dash5.png',
            '/dash6.png',
            '/dash7.png',
        ],
        videos: [
            '/dash1.png',
        ],
        about: 'This is a project to monitor presale transactions, contains an Admin Dashboard and User Dashboard pages built with Next.js, ethers.js, wagmi, TypeScript and Tailwind CSS',
        links: {
            live: '',
            github: 'https://github.com/akorede12/presaleDashboard',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'Ethers.js',
            'Wagmi',
        ],
        contributions: [
            'Implemented Multi-wallet support (MetaMask, Trust Wallet, Phantom, WalletConnect)',
            'Implemented Token Presale Management: Supports multiple phases (Pre-Sale, Public Sale, etc.)',
            'Implemented Secure connection handling with error states',
            'Implemented Automatic wallet detection and fallbacks',
            'Implemented Real-time presale statistics display',
            'Implemented Transaction history with detailed records',
            'Implemented Dynamic presale phase creation with configurable parameters',
            'Built responsive UI components',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack web3 Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '18',
        name: 'My Smart Contracts',
        description: 'My solidity smart contracts',
        mainImage: '/contracts.png',
        screenshots: [
            '/contracts.png',
        ],
        videos: [
            '/contracts.png',
        ],
        about: 'This is a collection of my solidity smart contracts',
        links: {
            live: '',
            github: 'https://github.com/akorede12/My-Smart-contracts',
            demo: '',
        },
        technologies: [
            'Solidity',
            'Hardhat',
            'Node.js',
        ],
        contributions: [
            'Built and deployed smart contracts',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '11',
        name: 'OnChain Votes',
        description: 'Secure and Transparent Voting Made Easy',
        mainImage: '/OnchainVotes.png',
        screenshots: [
            '/OnchainVotes.png',
        ],
        videos: [
            '/OnchainVotes.png',
        ],
        about: 'Experience the future of voting with OnChain Votes. My Next.js dapp that interacts with an EVM Election/Voting smart contract to enable seamless and secure elections. Create elections, add voters, define vote options, and cast votes effortlessly. Gain access to election details, allowed voters, and comprehensive reports on voter participation and choices. With OnChain Votes, you can trust in the integrity of your elections, thanks to a built-in "checker" library that validates vote options.',
        links: {
            live: '',
            github: 'https://github.com/akorede12/onchainVote',
            demo: '',
        },
        technologies: [
            'Next.js',
            'JavaScript',
            'Tailwind CSS',
            'Node.js',
            'ethers',
            'solidity',
            'wagmi',
        ],
        contributions: [
            'Built and deployed smart contracts',
            'Integrated smart contracts to frontend',
            'Built responsive UI components',
            'Optimized Websiteperformance',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '12',
        name: 'NFTicks',
        description: 'A secure way to purchase tickets to your favourite events.',
        mainImage: '/NFTicks.png',
        screenshots: [
            '/NFTicks.png',
        ],
        videos: [
            '/NFTicks.png',
        ],
        about: 'The NFTick.io is an NFT marketplace for event tickets, exposing NFTick buyers to their favourite events, and giving event planners an easy way to plan, create, monitor and make sales of tickets to their events on the platform powered by blockchain technology. Built using the erc1155 token standard and deployed to the polygon POS chain, here are some benefits of the NFTick.io platform',
        links: {
            live: '',
            github: 'https://github.com/akorede12/NFTicks',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'ethers',
            'hardhat',
        ],
        contributions: [
            'Built and deployed smart contracts',
            'Integrated smart contracts to frontend',
            'Built responsive UI components',
            'Optimized website performance',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Smart Contract Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'DevYemi Adeyanju Adeyemi',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '13',
        name: 'My Portfolio',
        description: "Akorede's Portfolio website",
        mainImage: '/portfolio.png',
        screenshots: [
            '/portfolio1.png',
            '/portfolio2.png',
            '/portfolio3.png',
            '/portfolio4.png',
            '/portfolio5.png',
        ],
        videos: [
            '/portfolio.png',
        ],
        about: 'This project is a portfolio website built with Next.js and Tailwind CSS',
        links: {
            live: 'https://akorede.qzz.io',
            github: 'https://github.com/akorede12/MyPorfolioV2',
            demo: 'https://my-portfolio-woad-theta.vercel.app/',
        },
        technologies: [
            'Next.js',
            'JavaScript',
            'Tailwind CSS',
            'Node.js',
        ],
        contributions: [
            'Built responsive UI components',
            'Optimized performance and SEO',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Web3 Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '14',
        name: 'NFT Marketplace',
        description: 'A modern e-commerce platform built with Next.js and Tailwind CSS',
        mainImage: '/MarketPlace.png',
        screenshots: [
            '/MarketPlace.png',
        ],
        videos: [
            '/MarketPlace.png',
        ],
        about: 'An NFT marketplace platform, frontend built with Nextjs and tailwindcss. Smart contract written in solidity and deployed with hardhat using javascript. IPFS is used for NFT image storage.',
        links: {
            live: '',
            github: 'https://github.com/akorede12/Akorede-s_NFT-Marketplace',
            demo: '',
        },
        technologies: [
            'Next.js',
            'JavaScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'ethers',
            'hardhat',
            'IPFS',
        ],
        contributions: [
            'Built and deployed NFT and Marketplace smart contracts',
            'Integrated smart contracts to frontend',
            'Built responsive UI components',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '6',
        name: 'BookingBox-Tx: Home, Hostel, Short-let Booking',
        description: 'Accomodation (Home, Hostel, Short-let) Booking onChain',
        mainImage: "/bookingBoxHero.png",
        screenshots: [
            '/bookingBoxHero.png',
        ],
        videos: [
            'https://youtu.be/zB7rabZADFQ',
        ],
        about: 'BookingBox-TX is a homestay/hotel booking Decentralized Application which leverages the power of Blockchain Technology. The smart contract is deployed on Lightlink Pegasus Testnet and the complete application is being built using technologies like Solidity, NextJS, Redux Toolkit, Hardhat and Ethers. The core of the contract is defined by three primary structures: ApartmentStruct, BookingStruct, and ReviewStruct, representing an apartment, a booking, and a review, respectively.',
        links: {
            live: '',
            github: "https://github.com/Ciphers-Harmony/BookingBox-TX",
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'Ethers',
            'hardhat',
            'RainbowKit Wallet',
            'Redux-Toolkit',
        ],
        contributions: [
            'Built and deployed BookingBox-Tx smart contracts',
            'BookingBox-Tx smart contracts integration to frontend',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Fullstack Web3 Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'max-clinch SULEMAN ISMAILA',
                role: 'Smart contract Developer',
                avatar: '/user.png',
            },
            {
                name: 'BrooklinDev',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '8',
        name: 'BlocQuest',
        description: 'A blockchain gamefi for learning and earning',
        mainImage: '/blocQuestHero.png',
        screenshots: [
            '/blocQuestHero.png',
        ],
        videos: [
            '/blocQuestHero.png',
        ],
        about: 'An Gamified Onchain Platform for learning and earning',
        links: {
            live: '',
            github: 'https://github.com/akorede12/WinByForce',
            demo: '',
        },
        technologies: [
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'Ethereum',
        ],
        contributions: [
            'Coordinated with the team to build the platform',
            'Integrated smart contracts to frontend',
            'Built and deployed smart contracts',
            'integrated wallet connect mechanism',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Web3 Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'max-clinch SULEMAN ISMAILA',
                role: 'Smart contract Developer',
                avatar: '/user.png',
            },
            {
                name: 'pheobeayo Ifeoluwa Sanni',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
            {
                name: 'VinceBrun Vincent-Bruno Neji',
                role: 'Frontend Developer',
                avatar: '/user.png',
            },
            {
                name: 'WinByForce Team',
                role: '',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '9',
        name: 'Greenvestor',
        description: 'Greenvestor is a web-based platform that operates on the web3 DEFI (Decentralized Finance) technology. It aims to connect individuals who want to borrow capital for sustainable projects with those who are interested in investing in these projects',
        mainImage: '/greenVestorHero.jpg',
        screenshots: [
            '/greenVestorHero.jpg',
        ],
        videos: [
            '/greenVestorHero.jpg',
        ],
        about: 'Greenvestor is a web-based platform that operates on the web3 DEFI (Decentralized Finance) technology. It aims to connect individuals who want to borrow capital for sustainable projects with those who are interested in investing in these projects. The platform allows users to explore a variety of sustainable projects and choose to invest in them or provide loans.These projects could involve areas like renewable energy, sustainable agriculture, or green technology.Users can browse through project listings, review project details, and assess their potential impact and financial viability. For individuals looking to invest, the platform offers investment options with different minimum amounts and expected returns.Users can select projects that align with their interests and financial goals.On the other hand, individuals with sustainable projects can create funding campaigns, providing information about their projects and setting funding targets. The platform ensures transparency and security by leveraging smart contracts on the Hedera network, a blockchain- based platform.Users can track the performance of their investments or funded projects, receiving regular updates and access to performance metrics.They can also participate in project discussions and collaborate with project creators. Overall, the project aims to facilitate the funding and investment process for sustainable projects while promoting transparency, trust, and community involvement through web3 DEFI technology.',
        links: {
            live: '',
            github: 'https://github.com/akorede12/greenvestor',
            demo: '',
        },
        technologies: [
            'Vite',
            'react',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'ethers',
            'solidity',
            'viem',
            'wagmi',
        ],
        contributions: [
            'Integrated wallet connect mechanism',
            'Coordinated with the team to build the platform',
            'Built and deployed smart contracts',
            'Integrated smart contracts to frontend',
            'Integrated hedera network',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'max-clinch SULEMAN ISMAILA',
                role: 'Smart contract Developer',
                avatar: '/user.png',
            },
            {
                name: 'And More',
                role: '',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '10',
        name: 'TAB Associates',
        description: 'Architects, Builders, Designers, Contractors.',
        mainImage: '/TABHero.png',
        screenshots: [
            '/TABHero.png',
        ],
        videos: [
            '/TABHero.png',
        ],
        about: 'TAB Associates: Architects, Builders, Designers, Contractors.',
        links: {
            live: 'https://tab-associates.vercel.app/',
            github: 'https://github.com/akorede12/Tab_Associates',
            demo: '',
        },
        technologies: [
            'Next.js',
            'JavaScript',
            'Tailwind CSS',
            'Node.js',
        ],
        contributions: [
            'Implemented Client desired specification',
            'Optimized performance and SEO',
            'Built responsive UI components',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Frontend Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '7',
        name: 'Acevote',
        description: 'OnChain Voting Platform',
        mainImage: '/AcevoteHero.jpg',
        screenshots: [
            '/AcevoteHero.jpg',
        ],
        videos: [
            '/AcevoteHero.jpg',
        ],
        about: 'Acevote is an onchain elections and voting platform',
        links: {
            live: '',
            github: 'https://github.com/akorede12/acevote-1',
            demo: 'https://youtu.be/n3F6sE7zsno',
        },
        technologies: [
            'React.js',
            'JavaScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'Ethereum',
        ],
        contributions: [
            'Coordinated with the team to build the platform',
            'Perform market research and analysis',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Co-founder',
                avatar: '/Me2.jpg',
            },
            {
                name: 'Acevote Team',
                role: '',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '15',
        name: 'Zell',
        description: 'NFT membership platform for e-commerce sellers',
        mainImage: '/zell.png',
        screenshots: [
            '/zell.png',
        ],
        videos: [
            '/zell.png',
        ],
        about: 'Zell is an NFT membership platform for e-commerce sellers. It provides a way for e-commerce sellers to engage with their buyers with the use of NFTs, the NFTs grants the buyers access to exclusive products, special sales or discounts on existing products.',
        links: {
            live: '',
            github: 'https://github.com/akorede12/Zell',
            demo: '',
        },
        technologies: [
            'no-code',
            'Adalo',
            'Solidity',
            'ethers',
            'hardhat',
        ],
        contributions: [
            'Built and deployed smart contracts',
            'Integrated smart contracts to frontend',
            'Built responsive UI components',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
            {
                name: 'Tamilore',
                role: 'Product Designer',
                avatar: '/user.png',
            },
            {
                name: 'Bright',
                role: 'Zell team',
                avatar: '/user.png',
            },
        ],
    },
    {
        id: '16',
        name: 'Whitelist Dapp',
        description: 'Whitelist Dapp built with Next.js and Tailwind CSS',
        mainImage: '/WhiteListDapp.png',
        screenshots: [
            '/WhiteListDapp.png',
        ],
        videos: [
            '/WhiteListDapp.png',
        ],
        about: 'A decentralized whitelist app that, whilelist users wallet addresses to grant users special access built with Next.js and Tailwind CSS',
        links: {
            live: '',
            github: 'https://github.com/akorede12/WhitelistDapp',
            demo: '',
        },
        technologies: [
            'Next.js',
            'JavaScript',
            'Tailwind CSS',
            'Node.js',
            'Solidity',
            'ethers',
            'hardhat',
        ],
        contributions: [
            'Built and deployed smart contracts',
            'Integrated smart contracts to frontend',
            'Built responsive UI components',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
    {
        id: '17',
        name: 'Wave Portal',
        description: 'Connect Ethereum wallet using MetaMask, send personalized messages, and wave to other users',
        mainImage: '/wavePortal.png',
        screenshots: [
            '/wavePortal.png',
        ],
        videos: [
            '/wavePortal.png',
        ],
        about: "This project is a React application that allows users to connect their Ethereum wallet using MetaMask, send personalized messages, and wave to other users. It interacts with a deployed smart contract on the Ethereum blockchain, allowing users to store and retrieve waves containing the sender's address, timestamp, and message.The application provides a user- friendly interface for engaging with the Ethereum network and visualizing the waves sent by various users. It was developed following instructions from buildspace's build-solidity-web3-app course.",
        links: {
            live: '',
            github: 'https://github.com/akorede12/Waveportal',
            demo: '',
        },
        technologies: [
            'React',
            'TypeScript',
            'Tailwind CSS',
            'Node.js',
            'solidity',
            'ethers',
            'hardhat',
        ],
        contributions: [
            'Built and deployed smart contracts',
            'Integrated smart contracts to frontend',
            'Built responsive UI components',
        ],
        contributors: [
            {
                name: 'Akorede',
                role: 'Full Stack Developer',
                avatar: '/Me2.jpg',
            },
        ],
    },
];

export default ProjectData;
